### ISSUE TITLE
question: implicit controller binding

### ISSUE THREAD

**Issue by 93578237** [Neoteroi/BlackSheep-MVC#9]
Hi, could you please explain, how it works? Application instance did not bind any controllers
https://github.com/Neoteroi/BlackSheepMVC/blob/a21c9abf08405470a2351cbb446f7041c07fc150/app/program.py#L7

**Comment by RobertoPrevato** [comment]
Hi!
Sure.

I wanted to enable this kind of syntax, when using the controllers pattern:

```python
from blacksheep.server.controllers import Controller, get


class Home(Controller):
    @get("/example")
    def example(self):
        return self.text("Hello, World!")
```

Note how the `get` decorator is imported and used to register a route.

The `get` decorator is a method of a singleton instance of `RoutesRegistry`, that is bound by default to all instances of `Application` class.

Request handlers registered this way are bound in memory to the singleton instance of `RoutesRegistry`. Controllers need to be imported by the code that configures the application, otherwise their code wouldn't be evaluated, and their request handlers could not be registered.

---

If you prefer an explicit approach, you can:

1. create your own instance of `RoutesRegistry`
2. use its decorator methods to register request handlers
3. configure the application to use your instance of `RoutesRegistry`, instead of the global one exposed by `blacksheep.server.controllers` module

```python
from blacksheep.server.routing import RoutesRegistry

controllers_router = RoutesRegistry()

# example: use @controllers.router.get() to register a request handler for HTTP GET to a certain route

app.controllers_router = controllers_router
```

---

I didn't want to make necessary to handle the `RoutesRegistry` when using controllers, so in this case I opted for a default global object that is used to register request handlers.
